import { DioceseName } from './SettingsService';
import centroids from '../data/dioceseCentroids.json';

// Turning a position coming from the phone into one of the dioceses the app knows.
//
// Every municipality is one point, its centroid, with the diocese it belongs to, and a position
// takes the diocese of the closest one. Dioceses are whole blocks of municipalities, so falling
// on a neighbouring municipality by mistake only changes the answer along a diocesan border,
// and that is the case this code refuses to answer instead of guessing.
//
// Nothing here talks to the phone, to the network or to the database: it is arithmetic over a
// table, so the whole of it can be checked from Jest without moving anywhere.
//
// The table is generated by scripts/buildDioceseTable.mjs. A municipality nobody has settled the
// diocese of yet is in it with diocese null, and lands here as no answer: knowing where somebody
// is and saying so is not the same as knowing which diocese they belong to.

export type Municipality = {
  name: string;
  latitude: number;
  longitude: number;
  // The comarca it is in, or the island or the country: it is what the table is grouped by when
  // somebody goes over it by hand, and what says where the work left is
  comarca: string;
  // null while nobody has settled which diocese it belongs to
  diocese: string | null;
};

// Further away than this from every municipality in the table, whoever is asking is outside the
// territory the app covers and there is nothing sensible to answer.
const MAXIMUM_DISTANCE_METERS = 30000;

const EARTH_RADIUS_METERS = 6371000;

function toRadians(degrees: number): number {
  return (degrees * Math.PI) / 180;
}

function distanceInMeters(latitude: number, longitude: number, otherLatitude: number, otherLongitude: number): number {
  const latitudeDifference = toRadians(otherLatitude - latitude);
  const longitudeDifference = toRadians(otherLongitude - longitude);
  const chord =
    Math.sin(latitudeDifference / 2) ** 2 +
    Math.cos(toRadians(latitude)) * Math.cos(toRadians(otherLatitude)) * Math.sin(longitudeDifference / 2) ** 2;
  return 2 * EARTH_RADIUS_METERS * Math.asin(Math.min(1, Math.sqrt(chord)));
}

// A diocese the settings would accept. It turns away both the ones nobody has settled, which are
// null, and a typo in the generated table, which would otherwise end up in a setting that
// SettingsService then refuses to save, leaving the diocese unchanged with nothing to show for it.
function isKnownDiocese(diocese: string | null): boolean {
  return diocese !== null && (Object.values(DioceseName) as string[]).includes(diocese);
}

/**
 * The diocese a position falls in, looked up in the table given, or null when there is no honest
 * answer: the position makes no sense, it is outside the territory, or it is so near a border
 * that its own margin of error reaches the other side.
 *
 * accuracyMeters is the radius the phone hands over together with the position (coords.accuracy).
 * When it is not known it counts as zero, that is, the position is taken at face value.
 *
 * Whoever calls this is meant to leave the diocese alone on a null, never to fall back to a guess.
 */
export function resolveDioceseIn(
  municipalities: Municipality[],
  latitude: number,
  longitude: number,
  accuracyMeters: number = 0,
): DioceseName | null {
  if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) {
    return null;
  }

  let nearest: Municipality | null = null;
  let nearestDistance = Number.POSITIVE_INFINITY;
  for (const municipality of municipalities) {
    const distance = distanceInMeters(latitude, longitude, municipality.latitude, municipality.longitude);
    if (distance < nearestDistance) {
      nearestDistance = distance;
      nearest = municipality;
    }
  }
  if (nearest === null || nearestDistance > MAXIMUM_DISTANCE_METERS || !isKnownDiocese(nearest.diocese)) {
    return null;
  }

  let nearestElsewhereDistance = Number.POSITIVE_INFINITY;
  for (const municipality of municipalities) {
    if (municipality.diocese === nearest.diocese) {
      continue;
    }
    const distance = distanceInMeters(latitude, longitude, municipality.latitude, municipality.longitude);
    if (distance < nearestElsewhereDistance) {
      nearestElsewhereDistance = distance;
    }
  }

  // The answer flips halfway between the two centroids, so that midpoint is how far the border
  // runs from here. A position whose margin of error reaches it is not worth trusting: any other
  // municipality of another diocese is farther still, so this is the nearest the answer can
  // change. With a single diocese in the table there is no border and nothing to doubt.
  //
  // A municipality nobody has settled counts as another diocese here, which is the cautious
  // reading: next to one of those, what is on the other side of the line is not known either.
  const distanceToTheBorder = (nearestElsewhereDistance - nearestDistance) / 2;
  if (accuracyMeters > distanceToTheBorder) {
    return null;
  }

  return nearest.diocese as DioceseName;
}

/**
 * The same, over the table the app ships with.
 */
export function resolveDiocese(latitude: number, longitude: number, accuracyMeters: number = 0): DioceseName | null {
  return resolveDioceseIn(centroids as Municipality[], latitude, longitude, accuracyMeters);
}

/**
 * The table the app ships with, for whoever needs to look at it as a whole.
 */
export function municipalitiesInTheTable(): Municipality[] {
  return centroids as Municipality[];
}
