import OfficeCommonPsalter from './OfficeCommonPsalter';
import InvitationCommonPsalter from './InvitationCommonPsalter';
import OfficeOfOrdinaryTime from './OfficeOfOrdinaryTime';
import PrayersOfOrdinaryTime from './PrayersOfOrdinaryTime';
import CommonPartsUntilFifthWeekOfLentTime from './CommonPartsUntilFifthWeekOfLentTime';
import PartsOfLentTime from './PartsOfLentTime';
import PartsOfFiveWeeksOfLentTime from './PartsOfFiveWeeksOfLentTime';
import CommonPartsOfHolyWeek from './CommonPartsOfHolyWeek';
import PalmSundayParts from './PalmSundayParts';
import PartsOfHolyWeek from './PartsOfHolyWeek';
import PartsOfEasterTriduum from './PartsOfEasterTriduum';
import PartsOfEasterBeforeAscension from './PartsOfEasterBeforeAscension';
import PartsOfEasterAfterAscension from './PartsOfEasterAfterAscension';
import PartsOfEasterOctave from './PartsOfEasterOctave';
import EasterWeekParts from './EasterWeekParts';
import AdventWeekParts from './AdventWeekParts';
import CommonAdventAndChristmasParts from './CommonAdventAndChristmasParts';
import AdventSundayParts from './AdventSundayParts';
import AdventFairDaysParts from './AdventFairDaysParts';
import ChristmasBeforeEpiphanyParts from './ChristmasBeforeEpiphanyParts';
import ChristmasWhenOctaveParts from './ChristmasWhenOctaveParts';
import AdventFairDaysAntiphons from './AdventFairDaysAntiphons';
import SpecialCommonPartsOfEasterSundays from './SpecialCommonPartsOfEasterSundays';
import LaudesCommonPsalter from './LaudesCommonPsalter';
import EasterSundayParts from './EasterSundayParts';
import EasterSunday from './EasterSunday';
import FiveWeeksOfSundayLentParts from './FiveWeeksOfSundayLentParts';
import VespersCommonPsalter from './VespersCommonPsalter';
import CommonHourPsalter from './CommonHourPsalter';
import SolemnityAndFestivityParts from './SolemnityAndFestivityParts';
import CommonNightPrayerPsalter from './CommonNightPrayerPsalter';
import CommonOfficeWhenStrongTimesPsalter from './CommonOfficeWhenStrongTimesPsalter';
import SaintsSolemnities from './SaintsSolemnities';
import SaintsMemories from './SaintsMemories';
import SpecialDaysParts from './SpecialDaysParts';
import CommonSpecialPartsOfEaster from './CommonSpecialPartsOfEaster';
import Various from './Various';

export default class LiturgyMasters {
  officeCommonPsalter: OfficeCommonPsalter;
  invitationCommonPsalter: InvitationCommonPsalter;
  officeOfOrdinaryTime: OfficeOfOrdinaryTime;
  prayersOfOrdinaryTime: PrayersOfOrdinaryTime;
  prayersOfOrdinaryTimeWhenFirstVespers: PrayersOfOrdinaryTime;
  commonPartsUntilFifthWeekOfLentTime: CommonPartsUntilFifthWeekOfLentTime;
  partsOfLentTime: PartsOfLentTime;
  partsOfFiveWeeksOfLentTime: PartsOfFiveWeeksOfLentTime;
  commonPartsOfHolyWeek: CommonPartsOfHolyWeek;
  palmSundayParts: PalmSundayParts;
  partsOfHolyWeek: PartsOfHolyWeek;
  partsOfEasterTriduum: PartsOfEasterTriduum;
  partsOfEasterBeforeAscension: PartsOfEasterBeforeAscension;
  partsOfEasterOctave: PartsOfEasterOctave;
  partsOfEasterAfterAscension: PartsOfEasterAfterAscension;
  easterWeekParts: EasterWeekParts;
  commonAdventAndChristmasParts: CommonAdventAndChristmasParts;
  adventWeekParts: AdventWeekParts;
  adventSundayParts: AdventSundayParts;
  adventFirstVespersOfSundayParts: AdventSundayParts;
  adventFairDaysParts: AdventFairDaysParts;
  adventFairDaysAntiphons: AdventFairDaysAntiphons;
  christmasWhenOctaveParts: ChristmasWhenOctaveParts;
  christmasBeforeEpiphanyParts: ChristmasBeforeEpiphanyParts;
  specialCommonPartsOfEasterSundays: SpecialCommonPartsOfEasterSundays;
  laudesCommonPsalter: LaudesCommonPsalter;
  commonSpecialPartsOfEaster: CommonSpecialPartsOfEaster;
  easterSundayParts: EasterSundayParts;
  easterFirstVespersOfSundayParts: EasterSundayParts;
  easterSunday: EasterSunday;
  fiveWeeksOfSundayLentParts: FiveWeeksOfSundayLentParts;
  fiveWeeksOfFirstsVespersOfSundayLentParts: FiveWeeksOfSundayLentParts;
  vespersCommonPsalter: VespersCommonPsalter;
  solemnityAndFestivityParts: SolemnityAndFestivityParts;
  solemnityAndFestivityWhenFirstVespersParts: SolemnityAndFestivityParts;
  commonHourPsalter: CommonHourPsalter;
  commonNightPrayerPsalter: CommonNightPrayerPsalter;
  commonOfficeWhenStrongTimesPsalter: CommonOfficeWhenStrongTimesPsalter;
  saintsSolemnities: SaintsSolemnities;
  saintsSolemnitiesWhenFirstsVespersParts: SaintsSolemnities;
  saintsMemories: SaintsMemories;
  specialDaysParts: SpecialDaysParts;
  various: Various;
}
