// "What does litcal call this date, under THIS calendar?" — for any calendar, not just the
// one the last migration ran with.
//
// The migration's manifest answers that question for a whole range, but for exactly one
// calendar: the diocese the join was run for. The day comparator lets you point the
// saints-app side at any calendar (that is the whole point of having two selectors), so it
// needs the same answer on demand.
//
// Rather than reimplement the lookup, this shells out to litcal's own
// `scripts/build-date-to-key-manifest.ts` for a one-day range. It is slower than a library
// call (a `tsx` start-up), but it is the very code the migration uses, so the comparator
// can never disagree with the manifest about what a date is. Answers are cached per
// calendar, so each date costs that start-up once.

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const LITCAL_ROOT = '/Users/pau/projects/saints/litcal';
const CALENDARS_DIR = path.join(LITCAL_ROOT, 'src/data/calendars');
const ALL_LAUDES = '/Users/pau/projects/saints/saints-app/src/store/db/day_specific_texts/all_laudes.json';
const CACHE_DIR = path.join(__dirname, '..', 'output/raw/litcal-days');
const MANIFEST_PATH = path.join(__dirname, '..', 'webui/run/date-to-key-manifest.json');
const LAST_RUN_PATH = path.join(__dirname, '..', 'webui/run/last-run.json');

function readJsonSafe(p, fallback = null) {
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch {
    return fallback;
  }
}

// Every calendar litcal can resolve against. The Catalan ones are generated by this
// migration; the rest ship with litcal.
function availableCalendars() {
  try {
    return fs
      .readdirSync(CALENDARS_DIR)
      .filter((f) => f.endsWith('.json'))
      .map((f) => f.replace(/\.json$/, ''))
      .sort();
  } catch {
    return [];
  }
}

function run(cmd, args, cwd) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { cwd });
    let out = '';
    child.stdout.on('data', (d) => (out += d));
    child.stderr.on('data', (d) => (out += d));
    child.on('close', (code) => resolve({ code, out }));
    child.on('error', (e) => resolve({ code: -1, out: out + String(e) }));
  });
}

const cachePath = (calendarId) => path.join(CACHE_DIR, `${calendarId.replace(/[^\w-]/g, '_')}.json`);

// The migration's own manifest is a free cache for its own calendar — and the one the day
// inspector already answers with, so reusing it keeps the two views in step.
function fromManifest(dateStr, calendarId) {
  const lastRun = readJsonSafe(LAST_RUN_PATH);
  if (!lastRun || lastRun.calendarId !== calendarId) return null;
  const manifest = readJsonSafe(MANIFEST_PATH, {});
  const entry = manifest[dateStr];
  return entry && entry.litcalId ? { litcalId: entry.litcalId, source: 'manifest' } : null;
}

async function resolveLitcalId(dateStr, calendarId) {
  const viaManifest = fromManifest(dateStr, calendarId);
  if (viaManifest) return viaManifest;

  const cacheFile = cachePath(calendarId);
  const cache = readJsonSafe(cacheFile, {}) || {};
  if (cache[dateStr]) return { litcalId: cache[dateStr], source: 'cache' };

  fs.mkdirSync(CACHE_DIR, { recursive: true });
  const tmp = path.join(CACHE_DIR, `.tmp-${calendarId.replace(/[^\w-]/g, '_')}-${dateStr}.json`);
  const result = await run(
    'npx',
    ['tsx', 'scripts/build-date-to-key-manifest.ts', ALL_LAUDES, dateStr, dateStr, tmp, calendarId],
    LITCAL_ROOT
  );
  const dump = readJsonSafe(tmp);
  try {
    fs.unlinkSync(tmp);
  } catch {}
  const litcalId = dump && dump[dateStr] ? dump[dateStr].litcalId : null;
  if (!litcalId) {
    return {
      litcalId: null,
      source: 'litcal',
      error: `litcal no ha pogut resoldre ${dateStr} amb el calendari "${calendarId}".`,
      log: result.out.slice(-1500),
    };
  }

  cache[dateStr] = litcalId;
  fs.writeFileSync(cacheFile, JSON.stringify(cache, null, 2), 'utf8');
  return { litcalId, source: 'litcal' };
}

module.exports = { resolveLitcalId, availableCalendars, LITCAL_ROOT };

if (require.main === module) {
  const [date, calendarId = 'spain'] = process.argv.slice(2);
  if (!date) {
    console.error('Usage: node migration-to-saints/lib/litcal-day.js YYYY-MM-DD [calendarId]');
    console.error(`Calendaris: ${availableCalendars().join(', ')}`);
    process.exit(1);
  }
  resolveLitcalId(date, calendarId).then((r) => {
    if (r.error) {
      console.error(r.error);
      console.error(r.log || '');
      process.exit(1);
    }
    console.log(`${date} · ${calendarId} → ${r.litcalId} (${r.source})`);
  });
}
