import OfficeCommonPsalter from "./OfficeCommonPsalter";
import InvitationCommonPsalter from "./InvitationCommonPsalter";
import OfficeOfOrdinaryTime from "./OfficeOfOrdinaryTime";
import PrayersOfOrdinaryTime from "./PrayersOfOrdinaryTime";
import CommonPartsUntilFifthWeekOfLentTime from "./CommonPartsUntilFifthWeekOfLentTime";
import PartsOfLentTime from "./PartsOfLentTime";
import PartsOfFiveWeeksOfLentTime from "./PartsOfFiveWeeksOfLentTime";
import CommonPartsOfHolyWeek from "./CommonPartsOfHolyWeek";
import PalmSundayParts from "./PalmSundayParts";
import PartsOfHolyWeek from "./PartsOfHolyWeek";
import PartsOfEasterTriduum from "./PartsOfEasterTriduum";
import PartsOfEasterBeforeAscension from "./PartsOfEasterBeforeAscension";
import PartsOfEasterAfterAscension from "./PartsOfEasterAfterAscension";
import PartsOfEasterOctave from "./PartsOfEasterOctave";
import EasterWeekParts from "./EasterWeekParts";
import AdventWeekParts from "./AdventWeekParts";
import CommonAdventAndChristmasParts from "./CommonAdventAndChristmasParts";
import AdventSundayParts from "./AdventSundayParts";
import AdventFairDaysParts from "./AdventFairDaysParts";
import ChristmasBeforeEpiphanyParts from "./ChristmasBeforeEpiphanyParts";
import ChristmasWhenOctaveParts from "./ChristmasWhenOctaveParts";
import AdventFairDaysAntiphons from "./AdventFairDaysAntiphons";
import SpecialCommonPartsOfEasterSundays from "./SpecialCommonPartsOfEasterSundays";
import LaudesCommonPsalter from "./LaudesCommonPsalter";
import EasterSundayParts from "./EasterSundayParts";
import EasterSunday from "./EasterSunday";
import FiveWeeksOfSundayLentParts from "./FiveWeeksOfSundayLentParts";
import VespersCommonPsalter from "./VespersCommonPsalter";
import CommonHourPsalter from "./CommonHourPsalter";
import SolemnityAndFestivityParts from "./SolemnityAndFestivityParts";
import CommonNightPrayerPsalter from "./CommonNightPrayerPsalter";
import CommonOfficeWhenStrongTimesPsalter from "./CommonOfficeWhenStrongTimesPsalter";
import SaintsSolemnities from "./SaintsSolemnities";
import SaintsMemories from "./SaintsMemories";
import SpecialDaysParts from "./SpecialDaysParts";
import CommonSpecialPartsOfEaster from "./CommonSpecialPartsOfEaster";
import Various from "./Various";

export default class LiturgyMasters{
    OfficeCommonPsalter: OfficeCommonPsalter;
    InvitationCommonPsalter: InvitationCommonPsalter;
    OfficeOfOrdinaryTime: OfficeOfOrdinaryTime;
    PrayersOfOrdinaryTime: PrayersOfOrdinaryTime;
    PrayersOfOrdinaryTimeWhenFirstVespers: PrayersOfOrdinaryTime;
    CommonPartsUntilFifthWeekOfLentTime: CommonPartsUntilFifthWeekOfLentTime;
    PartsOfLentTime: PartsOfLentTime;
    PartsOfFiveWeeksOfLentTime: PartsOfFiveWeeksOfLentTime;
    CommonPartsOfHolyWeek: CommonPartsOfHolyWeek;
    PalmSundayParts: PalmSundayParts;
    PartsOfHolyWeek: PartsOfHolyWeek;
    PartsOfEasterTriduum: PartsOfEasterTriduum;
    PartsOfEasterBeforeAscension: PartsOfEasterBeforeAscension;
    PartsOfEasterOctave: PartsOfEasterOctave;
    PartsOfEasterAfterAscension: PartsOfEasterAfterAscension;
    EasterWeekParts: EasterWeekParts;
    CommonAdventAndChristmasParts: CommonAdventAndChristmasParts;
    AdventWeekParts: AdventWeekParts;
    AdventSundayParts: AdventSundayParts;
    AdventFirstVespersOfSundayParts: AdventSundayParts;
    AdventFairDaysParts: AdventFairDaysParts;
    AdventFairDaysAntiphons: AdventFairDaysAntiphons;
    ChristmasWhenOctaveParts: ChristmasWhenOctaveParts;
    ChristmasBeforeEpiphanyParts: ChristmasBeforeEpiphanyParts;
    SpecialCommonPartsOfEasterSundays: SpecialCommonPartsOfEasterSundays;
    LaudesCommonPsalter: LaudesCommonPsalter;
    CommonSpecialPartsOfEaster: CommonSpecialPartsOfEaster;
    EasterSundayParts: EasterSundayParts;
    EasterFirstVespersOfSundayParts: EasterSundayParts;
    EasterSunday: EasterSunday;
    FiveWeeksOfSundayLentParts: FiveWeeksOfSundayLentParts;
    FiveWeeksOfFirstsVespersOfSundayLentParts: FiveWeeksOfSundayLentParts;
    VespersCommonPsalter: VespersCommonPsalter;
    SolemnityAndFestivityParts: SolemnityAndFestivityParts;
    SolemnityAndFestivityWhenFirstVespersParts: SolemnityAndFestivityParts;
    CommonHourPsalter: CommonHourPsalter;
    CommonNightPrayerPsalter: CommonNightPrayerPsalter;
    CommonOfficeWhenStrongTimesPsalter: CommonOfficeWhenStrongTimesPsalter;
    SaintsSolemnities: SaintsSolemnities;
    SaintsSolemnitiesWhenFirstsVespersParts: SaintsSolemnities;
    SaintsMemories: SaintsMemories;
    SpecialDaysParts: SpecialDaysParts;
    Various: Various;
}

