export default class PalmSundayParts {
    static MasterName: string = "tempsQuaresmaRams";

    constructor(databaseRow) {
        this. = databaseRow.id;
        this. = databaseRow.ant1Vespres1;
        this. = databaseRow.ant2Vespres1;
        this. = databaseRow.ant3Vespres1;
        this. = databaseRow.citaLBVespres;
        this. = databaseRow.lecturaBreuVespres;
        this. = databaseRow.respBreuVespres1;
        this. = databaseRow.respBreuVespres2;
        this. = databaseRow.respBreuVespres3;
        this. = databaseRow.antMaria1A;
        this. = databaseRow.antMaria1B;
        this. = databaseRow.antMaria1C;
        this. = databaseRow.pregariesVespres1;
        this. = databaseRow.oraFiVespres1;
        this. = databaseRow.respVOfici;
        this. = databaseRow.respROfici;
        this. = databaseRow.referencia1;
        this. = databaseRow.cita1;
        this. = databaseRow.titol1;
        this. = databaseRow.lectura1;
        this. = databaseRow.citaResp1;
        this. = databaseRow.resp1Part1;
        this. = databaseRow.resp1Part2;
        this. = databaseRow.resp1Part3;
        this. = databaseRow.referencia2;
        this. = databaseRow.cita2;
        this. = databaseRow.titol2;
        this. = databaseRow.lectura2;
        this. = databaseRow.versResp2;
        this. = databaseRow.resp2Part1;
        this. = databaseRow.resp2Part2;
        this. = databaseRow.resp2Part3;
        this. = databaseRow.ant1Laudes;
        this. = databaseRow.ant2Laudes;
        this. = databaseRow.ant3Laudes;
        this. = databaseRow.citaLBLaudes;
        this. = databaseRow.lecturaBreuLaudes;
        this. = databaseRow.respBreu1Laudes;
        this. = databaseRow.respBreu2Laudes;
        this. = databaseRow.respBreu3Laudes;
        this. = databaseRow.antZacariesA;
        this. = databaseRow.antZacariesB;
        this. = databaseRow.antZacariesC;
        this. = databaseRow.pregariesLaudes;
        this. = databaseRow.oraFiLaudes;
        this. = databaseRow.citaLBTercia;
        this. = databaseRow.lecturaBreuTercia;
        this. = databaseRow.respVTercia;
        this. = databaseRow.respRTercia;
        this. = databaseRow.citaLBSexta;
        this. = databaseRow.lecturaBreuSexta;
        this. = databaseRow.respVSexta;
        this. = databaseRow.respRSexta;
        this. = databaseRow.citaLBNona;
        this. = databaseRow.lecturaBreuNona;
        this. = databaseRow.respVNona;
        this. = databaseRow.respRNona;
        this. = databaseRow.ant1Vespres2;
        this. = databaseRow.ant2Vespres2;
        this. = databaseRow.ant3Vespres2;
        this. = databaseRow.citaLBVespres2;
        this. = databaseRow.lecturaBreuVespres2;
        this. = databaseRow.respBreuVespres12;
        this. = databaseRow.respBreuVespres22;
        this. = databaseRow.respBreuVespres32;
        this. = databaseRow.antMaria1A2;
        this. = databaseRow.antMaria1B2;
        this. = databaseRow.antMaria1C2;
        this. = databaseRow.pregariesVespres12;
        this. = databaseRow.oraFiVespres12;
    }

    Id: number;
    Antiphon: string;
}