export default class PartsOfEasterOctave {
    static MasterName: string = "tempsPasquaOct";

    constructor(databaseRow) {
        this. = databaseRow.id;
        this. = databaseRow.ant1Ofici;
        this. = databaseRow.titolSalm1Ofici;
        this. = databaseRow.salm1Ofici;
        this. = databaseRow.gloriaOfici1;
        this. = databaseRow.ant2Ofici;
        this. = databaseRow.titolSalm2Ofici;
        this. = databaseRow.salm2Ofici;
        this. = databaseRow.gloriaOfici2;
        this. = databaseRow.ant3Ofici;
        this. = databaseRow.titolSalm3Ofici;
        this. = databaseRow.salm3Ofici;
        this. = databaseRow.gloriaOfici3;
        this. = databaseRow.respVOfici;
        this. = databaseRow.respROfici;
        this. = databaseRow.referencia1;
        this. = databaseRow.citaLect1Ofici;
        this. = databaseRow.titolLect1Ofici;
        this. = databaseRow.lectura1;
        this. = databaseRow.citaResp1Ofici;
        this. = databaseRow.resp1Part1Ofici;
        this. = databaseRow.resp1Part2Ofici;
        this. = databaseRow.resp1Part3Ofici;
        this. = databaseRow.referencia2Ofici;
        this. = databaseRow.citaLect2Ofici;
        this. = databaseRow.titolLect2Ofici;
        this. = databaseRow.lectura2;
        this. = databaseRow.citaResp2Ofici;
        this. = databaseRow.resp2Part1Ofici;
        this. = databaseRow.resp2Part2Ofici;
        this. = databaseRow.resp2Part3Ofici;
        this. = databaseRow.citaLBLaudes;
        this. = databaseRow.lecturaBreuLaudes;
        this. = databaseRow.antEspecialLaudes;
        this. = databaseRow.antZacaries;
        this. = databaseRow.pregariesLaudes;
        this. = databaseRow.oraFiLaudes;
        this. = databaseRow.antMenorTercia;
        this. = databaseRow.antMenorSexta;
        this. = databaseRow.antMenorNona;
        this. = databaseRow.titol1salm117;
        this. = databaseRow.part1Salm117;
        this. = databaseRow.gloria1salm117;
        this. = databaseRow.titol2salm117;
        this. = databaseRow.part2Salm117;
        this. = databaseRow.gloria2salm117;
        this. = databaseRow.titol3salm117;
        this. = databaseRow.part3Salm117;
        this. = databaseRow.gloria3salm117;
        this. = databaseRow.citaLBTercia;
        this. = databaseRow.lecturaBreuTercia;
        this. = databaseRow.citaLBSexta;
        this. = databaseRow.lecturaBreuSexta;
        this. = databaseRow.citaLBNona;
        this. = databaseRow.lecturaBreuNona;
        this. = databaseRow.oraFiMenor;
        this. = databaseRow.citaLBVespres;
        this. = databaseRow.lecturaBreuVespres;
        this. = databaseRow.antEspecialVespres;
        this. = databaseRow.antMaria;
        this. = databaseRow.pregariesVespres;
        this. = databaseRow.oraFiVespres;
        this. = databaseRow.antCompletes;
    }

    Id: number;
    Antiphon: string;
}