export default class Various {
    static MasterName: string = "diversos";

    constructor(databaseTable: any = undefined) {
        if(databaseTable) {
            this.Psalm94 = databaseTable[0].oracio;
            this.TeDeumLatinAnthem = databaseTable[1].oracio;
            this.TeDeumCatalanAnthem = databaseTable[2].oracio;
            this.LaudesEvangelicalChant = databaseTable[3].oracio;
            this.OurFatherPrayer = databaseTable[4].oracio;
            this.VespersEvangelicalChant = databaseTable[5].oracio;
            this.ThirdHourLatinFirstOptionAnthem = databaseTable[6].oracio;
            this.ThirdHourCatalanFirstOptionAnthem = databaseTable[7].oracio;
            this.ThirdHourLatinSecondOptionAnthem = databaseTable[8].oracio;
            this.ThirdHourCatalanSecondOptionAnthem = databaseTable[9].oracio;
            this.SixthHourLatinFirstOptionAnthem = databaseTable[10].oracio;
            this.SixthHourCatalanFirstOptionAnthem = databaseTable[11].oracio;
            this.SixthHourLatinSecondOptionAnthem = databaseTable[12].oracio;
            this.SixthHourCatalSecondOptionAnthem = databaseTable[13].oracio;
            this.NinthHourLatinFirstOptionAnthem = databaseTable[14].oracio;
            this.NinthHourCatalanFirstOptionAnthem = databaseTable[15].oracio;
            this.NinthHourLatinSecondOptionAnthem = databaseTable[16].oracio;
            this.NinthHourCatalanSecondOptionAnthem = databaseTable[17].oracio;
            this.NightPrayerLatinFirstOptionAnthem = databaseTable[18].oracio;
            this.NightPrayerCatalanFirstOptionAnthem = databaseTable[19].oracio;
            this.NightPrayerLatinSecondOptionAnthem = databaseTable[20].oracio;
            this.NightPrayerCatalanSecondOptionAnthem = databaseTable[21].oracio;
            this.NightPrayerEvangelicalChant = databaseTable[22].oracio;
            this.NightPrayerFinalAntiphonLatinFirstOption = databaseTable[23].oracio;
            this.NightPrayerFinalAntiphonCatalanFirstOption = databaseTable[24].oracio;
            this.NightPrayerFinalAntiphonLatinSecondOption = databaseTable[25].oracio;
            this.NightPrayerFinalAntiphonCatalanSecondOption = databaseTable[26].oracio;
            this.NightPrayerFinalAntiphonLatinThirdOption = databaseTable[27].oracio;
            this.NightPrayerFinalAntiphonCatalanThirdOption = databaseTable[28].oracio;
            this.NightPrayerFinalAntiphonLatinFourthOption = databaseTable[29].oracio;
            this.NightPrayerFinalAntiphonCatalanFourthOption = databaseTable[30].oracio;
            this.NightPrayerFinalAntiphonLatinFifthOption = databaseTable[31].oracio;
            this.NightPrayerFinalAntiphonCatalanFifthOption = databaseTable[32].oracio;
            this.SpecialVesperChant = databaseTable[33].oracio;
            this.Psalm99 = databaseTable[34].oracio;
            this.Psalm66 = databaseTable[35].oracio;
            this.Psalm23 = databaseTable[36].oracio;
            this.PenitentialAct = databaseTable[37].oracio;
            this.Pope = databaseTable[38].oracio;
            this.BarcelonaBishop = databaseTable[39].oracio;
            this.GironaBishop = databaseTable[40].oracio;
            this.LleidaBishop = databaseTable[41].oracio;
            this.SantFeliuBishop = databaseTable[42].oracio;
            this.SolsonaBishop = databaseTable[43].oracio;
            this.TarragonaBishop = databaseTable[44].oracio;
            this.TerrassaBishop = databaseTable[45].oracio;
            this.TortosaBishop = databaseTable[46].oracio;
            this.UrgellBishop = databaseTable[47].oracio;
            this.VicBishop = databaseTable[48].oracio;
            this.AndorraBishop = databaseTable[49].oracio;
            this.MallorcaBishop = databaseTable[50].oracio;
        }
    }
    Psalm94: string;
    TeDeumLatinAnthem: string;
    TeDeumCatalanAnthem: string;
    LaudesEvangelicalChant: string;
    OurFatherPrayer: string;
    VespersEvangelicalChant: string;
    ThirdHourLatinFirstOptionAnthem: string;
    ThirdHourCatalanFirstOptionAnthem: string;
    ThirdHourLatinSecondOptionAnthem: string;
    ThirdHourCatalanSecondOptionAnthem: string;
    SixthHourLatinFirstOptionAnthem: string;
    SixthHourCatalanFirstOptionAnthem: string;
    SixthHourLatinSecondOptionAnthem: string;
    SixthHourCatalSecondOptionAnthem: string;
    NinthHourLatinFirstOptionAnthem: string;
    NinthHourCatalanFirstOptionAnthem: string;
    NinthHourLatinSecondOptionAnthem: string;
    NinthHourCatalanSecondOptionAnthem: string;
    NightPrayerLatinFirstOptionAnthem: string;
    NightPrayerCatalanFirstOptionAnthem: string;
    NightPrayerLatinSecondOptionAnthem: string;
    NightPrayerCatalanSecondOptionAnthem: string;
    NightPrayerEvangelicalChant: string;
    NightPrayerFinalAntiphonLatinFirstOption: string;
    NightPrayerFinalAntiphonCatalanFirstOption: string;
    NightPrayerFinalAntiphonLatinSecondOption: string;
    NightPrayerFinalAntiphonCatalanSecondOption: string;
    NightPrayerFinalAntiphonLatinThirdOption: string;
    NightPrayerFinalAntiphonCatalanThirdOption: string;
    NightPrayerFinalAntiphonLatinFourthOption: string;
    NightPrayerFinalAntiphonCatalanFourthOption: string;
    NightPrayerFinalAntiphonLatinFifthOption: string;
    NightPrayerFinalAntiphonCatalanFifthOption: string;
    SpecialVesperChant: string;
    Psalm99: string;
    Psalm66: string;
    Psalm23: string;
    PenitentialAct: string;
    Pope: string;
    BarcelonaBishop: string;
    GironaBishop: string;
    LleidaBishop: string;
    SantFeliuBishop: string;
    SolsonaBishop: string;
    TarragonaBishop: string;
    TerrassaBishop: string;
    TortosaBishop: string;
    UrgellBishop: string;
    VicBishop: string;
    AndorraBishop: string;
    MallorcaBishop: string;
}
