export default class Various {
    static MasterName: string = "diversos";

    constructor(databaseTable: any = undefined) {
        if(databaseTable) {
            this.Psalm94 = databaseTable.item(0).oracio;
            this.TeDeumLatinAnthem = databaseTable.item(1).oracio;
            this.TeDeumCatalanAnthem = databaseTable.item(2).oracio;
            this.LaudesEvangelicalChant = databaseTable.item(3).oracio;
            this.OurFatherPrayer = databaseTable.item(4).oracio;
            this.VespersEvangelicalChant = databaseTable.item(5).oracio;
            this.ThirdHourLatinFirstOptionAnthem = databaseTable.item(6).oracio;
            this.ThirdHourCatalanFirstOptionAnthem = databaseTable.item(7).oracio;
            this.ThirdHourLatinSecondOptionAnthem = databaseTable.item(8).oracio;
            this.ThirdHourCatalanSecondOptionAnthem = databaseTable.item(9).oracio;
            this.SixthHourLatinFirstOptionAnthem = databaseTable.item(10).oracio;
            this.SixthHourCatalanFirstOptionAnthem = databaseTable.item(11).oracio;
            this.SixthHourLatinSecondOptionAnthem = databaseTable.item(12).oracio;
            this.SixthHourCatalSecondOptionAnthem = databaseTable.item(13).oracio;
            this.NinthHourLatinFirstOptionAnthem = databaseTable.item(14).oracio;
            this.NinthHourCatalanFirstOptionAnthem = databaseTable.item(15).oracio;
            this.NinthHourLatinSecondOptionAnthem = databaseTable.item(16).oracio;
            this.NinthHourCatalanSecondOptionAnthem = databaseTable.item(17).oracio;
            this.NightPrayerLatinFirstOptionAnthem = databaseTable.item(18).oracio;
            this.NightPrayerCatalanFirstOptionAnthem = databaseTable.item(19).oracio;
            this.NightPrayerLatinSecondOptionAnthem = databaseTable.item(20).oracio;
            this.NightPrayerCatalanSecondOptionAnthem = databaseTable.item(21).oracio;
            this.NightPrayerEvangelicalChant = databaseTable.item(22).oracio;
            this.NightPrayerFinalAntiphonLatinFirstOption = databaseTable.item(23).oracio;
            this.NightPrayerFinalAntiphonCatalanFirstOption = databaseTable.item(24).oracio;
            this.NightPrayerFinalAntiphonLatinSecondOption = databaseTable.item(25).oracio;
            this.NightPrayerFinalAntiphonCatalanSecondOption = databaseTable.item(26).oracio;
            this.NightPrayerFinalAntiphonLatinThirdOption = databaseTable.item(27).oracio;
            this.NightPrayerFinalAntiphonCatalanThirdOption = databaseTable.item(28).oracio;
            this.NightPrayerFinalAntiphonLatinFourthOption = databaseTable.item(29).oracio;
            this.NightPrayerFinalAntiphonCatalanFourthOption = databaseTable.item(30).oracio;
            this.NightPrayerFinalAntiphonLatinFifthOption = databaseTable.item(31).oracio;
            this.NightPrayerFinalAntiphonCatalanFifthOption = databaseTable.item(32).oracio;
            this.SpecialVesperChant = databaseTable.item(33).oracio;
            this.Psalm99 = databaseTable.item(34).oracio;
            this.Psalm66 = databaseTable.item(35).oracio;
            this.Psalm23 = databaseTable.item(36).oracio;
            this.PenitentialAct = databaseTable.item(37).oracio;
            this.Pope = databaseTable.item(38).oracio;
            this.BarcelonaBishop = databaseTable.item(39).oracio;
            this.GironaBishop = databaseTable.item(40).oracio;
            this.LleidaBishop = databaseTable.item(41).oracio;
            this.SantFeliuBishop = databaseTable.item(42).oracio;
            this.SolsonaBishop = databaseTable.item(43).oracio;
            this.TarragonaBishop = databaseTable.item(44).oracio;
            this.TerrassaBishop = databaseTable.item(45).oracio;
            this.TortosaBishop = databaseTable.item(46).oracio;
            this.UrgellBishop = databaseTable.item(47).oracio;
            this.VicBishop = databaseTable.item(48).oracio;
            this.AndorraBishop = databaseTable.item(49).oracio;
            this.MallorcaBishop = databaseTable.item(50).oracio;
        }
    }
    Psalm94: string;
    TeDeumLatinAnthem: string;
    TeDeumCatalanAnthem: string;
    LaudesEvangelicalChant: string;
    OurFatherPrayer: string;
    VespersEvangelicalChant: string;
    ThirdHourLatinFirstOptionAnthem: string;
    ThirdHourCatalanFirstOptionAnthem: string;
    ThirdHourLatinSecondOptionAnthem: string;
    ThirdHourCatalanSecondOptionAnthem: string;
    SixthHourLatinFirstOptionAnthem: string;
    SixthHourCatalanFirstOptionAnthem: string;
    SixthHourLatinSecondOptionAnthem: string;
    SixthHourCatalSecondOptionAnthem: string;
    NinthHourLatinFirstOptionAnthem: string;
    NinthHourCatalanFirstOptionAnthem: string;
    NinthHourLatinSecondOptionAnthem: string;
    NinthHourCatalanSecondOptionAnthem: string;
    NightPrayerLatinFirstOptionAnthem: string;
    NightPrayerCatalanFirstOptionAnthem: string;
    NightPrayerLatinSecondOptionAnthem: string;
    NightPrayerCatalanSecondOptionAnthem: string;
    NightPrayerEvangelicalChant: string;
    NightPrayerFinalAntiphonLatinFirstOption: string;
    NightPrayerFinalAntiphonCatalanFirstOption: string;
    NightPrayerFinalAntiphonLatinSecondOption: string;
    NightPrayerFinalAntiphonCatalanSecondOption: string;
    NightPrayerFinalAntiphonLatinThirdOption: string;
    NightPrayerFinalAntiphonCatalanThirdOption: string;
    NightPrayerFinalAntiphonLatinFourthOption: string;
    NightPrayerFinalAntiphonCatalanFourthOption: string;
    NightPrayerFinalAntiphonLatinFifthOption: string;
    NightPrayerFinalAntiphonCatalanFifthOption: string;
    SpecialVesperChant: string;
    Psalm99: string;
    Psalm66: string;
    Psalm23: string;
    PenitentialAct: string;
    Pope: string;
    BarcelonaBishop: string;
    GironaBishop: string;
    LleidaBishop: string;
    SantFeliuBishop: string;
    SolsonaBishop: string;
    TarragonaBishop: string;
    TerrassaBishop: string;
    TortosaBishop: string;
    UrgellBishop: string;
    VicBishop: string;
    AndorraBishop: string;
    MallorcaBishop: string;
}